### ISSUE TITLE
Make new next-level pasting option listen to corresponding setting

### ISSUE THREAD

**Issue by vlunn** [sweng-group-3/transmission#10]

**Comment by varesa2** [comment]
Combined work by @ile6695 from #8 and @AnnaJasminAnttila from #9 so that the feature respects the selection made in preferences.

Some obstacles:
- Upstream uses functionality deprecated in current Qt version so it didn't compile on my workstation since I updated last week. Had to set up an alternative build environment with an older Qt
- Ended up hitting and filing a use-after-free bug in the preferences dialog in the upstream master branch: https://github.com/transmission/transmission/issues/1631

Time spent: 5h
